/*******************************************************************************
 * Copyright (c) 2000, 2005 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.corext.fix;

import java.util.List;
import java.util.Map;

import org.eclipse.text.edits.TextEdit;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.NullProgressMonitor;

import org.eclipse.jface.text.Document;
import org.eclipse.jface.text.IDocument;

import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.core.dom.CompilationUnit;
import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;

import org.eclipse.jdt.internal.corext.codemanipulation.ImportRewrite;
import org.eclipse.jdt.internal.corext.codemanipulation.NewImportRewrite;


public abstract class AbstractFix implements IFix {
	
	public interface IFixRewriteOperation {
		public void rewriteAST(
				ASTRewrite rewrite, 
				NewImportRewrite importRewrite, 
				CompilationUnit compilationUnit,
				List/*<TextEditGroup>*/ textEditGroups) throws CoreException;
	}
	
	private final String fName;
	private final ICompilationUnit fCompilationUnit;
	
	protected AbstractFix(String name, ICompilationUnit compilationUnit) {
		fName= name;
		fCompilationUnit= compilationUnit;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.jdt.internal.corext.fix.IFix#getName()
	 */
	public String getDescription() {
		return fName;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.jdt.internal.corext.fix.IFix#getCompilationUnit()
	 */
	public ICompilationUnit getCompilationUnit() {
		return fCompilationUnit;
	}
	
	/**
	 * Helper to apply a <code>ASTRewrite</code> and a <code>ImportRewrite</code> to a 
	 * <code>ICompilationUnit</code> to calculate a <code>TextEdit</code> generated by
	 * the rewrite.
	 * 
	 * @param compilationUnit The compilationUnit to apply to, not null
	 * @param rewrite The rewrite to apply, not null
	 * @param imports Import rewrites to apply, may be null
	 * @return The TextEdit
	 * @throws CoreException
	 * @deprecated
	 */
	protected TextEdit applyEdits(ICompilationUnit compilationUnit, ASTRewrite rewrite, ImportRewrite imports) throws CoreException {
		Map options= compilationUnit.getJavaProject().getOptions(true);
		IDocument document1= new Document(compilationUnit.getBuffer().getContents());
		TextEdit edit= rewrite.rewriteAST(document1, options);

		if (imports != null && !imports.isEmpty()) {
			edit.addChild(imports.createEdit(document1, new NullProgressMonitor()));
		}
		return edit;
	}
	
	/**
	 * Helper to apply a <code>ASTRewrite</code> and a <code>ImportRewrite</code> to a 
	 * <code>ICompilationUnit</code> to calculate a <code>TextEdit</code> generated by
	 * the rewrite.
	 * 
	 * @param compilationUnit The compilationUnit to apply to, not null
	 * @param rewrite The rewrite to apply, not null
	 * @param imports Import rewrites to apply, may be null
	 * @return The TextEdit
	 * @throws CoreException
	 */
	protected TextEdit applyEdits(CompilationUnit compilationUnit, ASTRewrite rewrite, NewImportRewrite imports) throws CoreException {
		TextEdit edit= rewrite.rewriteAST();

		if (imports != null) {
			edit.addChild(imports.rewriteImports(new NullProgressMonitor()));
		}
		return edit;
	}
}
