/*******************************************************************************
 * Copyright (c) 2000, 2005 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.corext.fix;

import java.util.Map;

import org.eclipse.text.edits.TextEdit;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.NullProgressMonitor;

import org.eclipse.core.filebuffers.FileBuffers;
import org.eclipse.core.filebuffers.ITextFileBufferManager;

import org.eclipse.jface.text.IDocument;

import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.core.dom.CompilationUnit;
import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;

import org.eclipse.jdt.internal.corext.codemanipulation.ImportRewrite;
import org.eclipse.jdt.internal.corext.codemanipulation.NewImportRewrite;


public abstract class AbstractFix implements IFix {
	
	private final String fName;
	private final ICompilationUnit fCompilationUnit;
	
	protected AbstractFix(String name, ICompilationUnit compilationUnit) {
		fName= name;
		fCompilationUnit= compilationUnit;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.jdt.internal.corext.fix.IFix#getName()
	 */
	public String getDescription() {
		return fName;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.jdt.internal.corext.fix.IFix#getCompilationUnit()
	 */
	public ICompilationUnit getCompilationUnit() {
		return fCompilationUnit;
	}
	
	/**
	 * Helper to apply a <code>ASTRewrite</code> and a <code>ImportRewrite</code> to a 
	 * <code>ICompilationUnit</code> to calculate a <code>TextEdit</code> generated by
	 * the rewrite.
	 * 
	 * @param compilationUnit The compilationUnit to apply to, not null
	 * @param rewrite The rewrite to apply, not null
	 * @param imports Import rewrites to apply, may be null
	 * @return The TextEdit
	 * @throws CoreException
	 */
	protected TextEdit applyEdits(ICompilationUnit compilationUnit, ASTRewrite rewrite, ImportRewrite imports) throws CoreException {
		ITextFileBufferManager manager= FileBuffers.getTextFileBufferManager();
		IPath path= compilationUnit.getPath();
		manager.connect(path, null);
		try {
			IDocument document= manager.getTextFileBuffer(path).getDocument();
			
			Map options= compilationUnit.getJavaProject().getOptions(true);
			TextEdit edit= rewrite.rewriteAST(document, options);
	
			if (imports != null && !imports.isEmpty()) {
				edit.addChild(imports.createEdit(document, new NullProgressMonitor()));
			}
			return edit;
		} finally {
			manager.disconnect(path, null);
		}
	}
	
	/**
	 * Helper to apply a <code>ASTRewrite</code> and a <code>ImportRewrite</code> to a 
	 * <code>ICompilationUnit</code> to calculate a <code>TextEdit</code> generated by
	 * the rewrite.
	 * 
	 * @param compilationUnit The compilationUnit to apply to, not null
	 * @param rewrite The rewrite to apply, not null
	 * @param imports Import rewrites to apply, may be null
	 * @return The TextEdit
	 * @throws CoreException
	 */
	protected TextEdit applyEdits(CompilationUnit compilationUnit, ASTRewrite rewrite, NewImportRewrite imports) throws CoreException {
		TextEdit edit= rewrite.rewriteAST();
		if (imports != null) {
			edit.addChild(imports.rewriteImports(new NullProgressMonitor()));
		}
		return edit;
	}
}
